button_l1: NOTHING
button_l2: NOTHING
button_left: NOTHING
button_right: NOTHING
button_share: NOTHING
button_options: NOTHING
button_pad: NOTHING


button_r1: NOTHING
button_x: NOTHING

button_r2: NOTHING
button_bot: NOTHING
button_top: NOTHING
button_o: NOTHING
button_rect: NOTHING


button_tri: NOTHING


button_l3: NOTHING
button_r3: NOTHING